#!/bin/bash

# DigiFort Labs - "One-Click" Production Deployment (ROBUST v3)
# -----------------------------------------------------------
# This script ensures the server exactly matches the repository.
# Usage: ./deploy_prod.sh

# Exit immediately if a command exits with a non-zero status.
set -e

# Define root directory (ensure we are in the project root)
PROJECT_ROOT="/home/ec2-user/digifortlabs"
echo "🚀 Starting Deployment in $PROJECT_ROOT"

# --- 0. FORCE GIT SYNC ---
echo "🔄 [0/6] Syncing with Repository (origin/master)..."
cd $PROJECT_ROOT
git fetch origin
git reset --hard origin/master
echo "✅ Git Sync Complete. Current commit: $(git rev-parse --short HEAD)"

# --- 1. SYSTEM CLEANUP ---
echo "🧹 [1/6] Cleaning legacy files & artifacts..."
# Specific cleanup for items being removed in this version
rm -rf Logo .vscode .agent .gemini digifortlabs.db
rm -rf check_users.py manual_setup.sh run_local.bat setup_ssl.sh fix_deployment.sh
rm -rf backend/tests frontend/__tests__

# System-wide cleanup
sudo dnf clean all
rm -rf ~/.cache ~/.npm
if command -v docker &> /dev/null; then sudo docker system prune -f; fi

# Dependency Check (Node 20 & Python)
CURRENT_NODE=$(node -v 2>/dev/null || echo "not found")
if [[ "$CURRENT_NODE" != v20* ]]; then
    echo "📦 Installing/Upgrading Node.js to v20..."
    sudo dnf remove -y nodejs || true
    curl -fsSL https://rpm.nodesource.com/setup_20.x | sudo bash -
    sudo dnf install -y nodejs
fi
sudo dnf install -y git python3 python3-pip nginx pm2 augeas-libs unzip || true
if ! command -v pm2 &> /dev/null; then sudo npm install -g pm2; fi

# --- 2. FRONTEND DEPLOYMENT ---
echo "🎨 [2/6] Building Frontend..."
cd $PROJECT_ROOT/frontend

# Kill existing process and free port 3000
pm2 delete frontend 2>/dev/null || true
sudo fuser -k 3000/tcp 2>/dev/null || true

# Build
rm -rf node_modules .next
echo "NEXT_PUBLIC_API_URL=https://digifortlabs.com/api" > .env.production
export NEXT_PUBLIC_API_URL=https://digifortlabs.com/api

npm install
npm run build

# Start with PM2
pm2 start npm --name "frontend" -- start
echo "✅ Frontend is Live on port 3000."

# --- 3. BACKEND DEPLOYMENT ---
echo "⚙️  [3/6] Setting up Backend..."
cd $PROJECT_ROOT/backend

# Kill existing process and free port 8000
pm2 delete backend 2>/dev/null || true
sudo fuser -k 8000/tcp 2>/dev/null || true

# Virtual Env & Dependencies
if [ ! -d ".venv" ]; then python3 -m venv .venv; fi
source .venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt

# --- 4. BACKEND CONFIGURATION (.env) ---
echo "📝 [4/6] Creating Backend Production Config..."
cat > .env <<'EOF'
# AUTO-GENERATED BY deploy_prod.sh - $(date)
POSTGRES_USER=postgres
POSTGRES_PASSWORD=Digif0rtlab$
POSTGRES_SERVER=digifort-db.crs4e62wi3w2.ap-south-1.rds.amazonaws.com
POSTGRES_PORT=5432
POSTGRES_DB=postgres
DATABASE_URL=postgresql://postgres:Digif0rtlab$@digifort-db.crs4e62wi3w2.ap-south-1.rds.amazonaws.com:5432/postgres

SECRET_KEY=production_key_digifort_redeploy_2026
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=43200

ENVIRONMENT=production
BACKEND_URL=https://digifortlabs.com/api
ENCRYPTION_KEY=a1z-3mNXYRp0yKAcP6xVpX6pjK6O38h039zisZMjE1U=

AWS_REGION=ap-south-1
AWS_BUCKET_NAME=digifort-labs-files
# NOTE: Set these on your server in backend/.env for S3 to work:
# AWS_ACCESS_KEY_ID=
# AWS_SECRET_ACCESS_KEY=

ICD11_CLIENT_ID=0079dc17-fdb9-4828-a400-643797eb1df0_a8a3014a-7bc9-410a-bbea-d42f56708b73
ICD11_CLIENT_SECRET=1BAnxHk7O8f7A7xM6UAnxHk7A77Hj4e6
EOF

# --- 5. DATABASE SCHEMA SYNC ---
echo "🛠️  [5/6] Syncing Database Schema..."
python fix_db_schema.py || echo "⚠️ Warning: Schema check skipped or failed."
deactivate

# --- 6. LAUNCH BACKEND & NGINX ---
echo "🚀 [6/6] Finalizing Launch..."
UVICORN_CMD="$PROJECT_ROOT/backend/.venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000 --proxy-headers --forwarded-allow-ips '*'"
pm2 start "$UVICORN_CMD" --name "backend"

# Save PM2 state
pm2 save

# Restart Nginx
sudo systemctl enable nginx
sudo systemctl restart nginx

echo "---------------------------------------------------"
echo "🎉 DEPLOYMENT SUCCESSFUL!"
echo "---------------------------------------------------"
echo "URL: https://digifortlabs.com"
echo "---------------------------------------------------"
pm2 status