version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://digifortlabs.com/api
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production

  evolution_api:
    image: atendai/evolution-api:v2.2.1
    container_name: evolution_api
    network_mode: "host"
    restart: always
    volumes:
      - ./evolution_instances:/evolution/instances
    environment:
      - SERVER_URL=http://localhost:8080
      - AUTH_TYPE=apikey
      - API_KEY_GLOBAL=DIGIFORT_SECURE_KEY_123
      - LOG_LEVEL=ERROR
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://digifort_admin:Digif0rtlab$@127.0.0.1:5432/digifort_db
