from typing import Optional

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import desc
from sqlalchemy.orm import Session

from ..database import get_db
from ..models import AuditLog, User, UserRole
from .auth import get_current_user

router = APIRouter()

@router.get("/logs")
def get_audit_logs(
    hospital_id: Optional[int] = None,
    page: int = 1,
    page_size: int = 50,
    db: Session = Depends(get_db), 
    current_user: User = Depends(get_current_user)
):
    if current_user.role not in [UserRole.SUPER_ADMIN, UserRole.HOSPITAL_ADMIN]:
        raise HTTPException(status_code=403, detail="Not authorized")
    
    query = db.query(AuditLog)
    
    # If Hospital Admin, enforce filter by their hospital
    if current_user.role == UserRole.HOSPITAL_ADMIN:
        # Filter logs generated by users of the same hospital
        query = query.join(User).filter(User.hospital_id == current_user.hospital_id)
    
    # If Super Admin provides hospital_id filter
    elif hospital_id:
        query = query.join(User).filter(User.hospital_id == hospital_id)

    total = query.count()
    logs = query.order_by(desc(AuditLog.timestamp)).offset((page - 1) * page_size).limit(page_size).all()
    
    return {
        "logs": logs,
        "total": total,
        "page": page,
        "pages": (total + page_size - 1) // page_size
    }
