"""Add all missing columns

Revision ID: 12f4756b64c0
Revises: e00d904c0a50
Create Date: 2026-07-07 15:23:21.212334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12f4756b64c0'
down_revision: Union[str, None] = 'e00d904c0a50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communication_logs', schema=None) as batch_op:
        pass

    with op.batch_alter_table('dental_3d_scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=False))

    with op.batch_alter_table('dental_lab_orders', schema=None) as batch_op:
        pass

    with op.batch_alter_table('dental_treatment_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=False))

    with op.batch_alter_table('doctor_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ipd_charge', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ipd_charge_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_residential', sa.Boolean(), nullable=True))

    with op.batch_alter_table('doctor_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_type', sa.String(), nullable=True))

    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_generation_settings', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('trial_ends_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_onboarded', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('patient_registration_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('nursing_base_charge', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ot_base_charge', sa.Float(), nullable=True))

    with op.batch_alter_table('insurance_claims', schema=None) as batch_op:
        pass

    with op.batch_alter_table('ipd_admissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fluid_balance_log', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('pre_op_assessment', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('post_op_assessment', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('diet_orders', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('bed_history', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('medical_cleared', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pharmacy_cleared', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('billing_cleared', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ot_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_mediclaim', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('mediclaim_details', sa.String(), nullable=True))

    with op.batch_alter_table('opd_visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_mediclaim', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('mediclaim_details', sa.String(), nullable=True))

    with op.batch_alter_table('operation_theaters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_surgery_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('current_anesthesia_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('anesthesiologist_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_diagnosis', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('special_requirements', sa.Text(), nullable=True))

    with op.batch_alter_table('ortho_records', schema=None) as batch_op:
        pass

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('periodontal_exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mfa_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('subdomain', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_subdomain'), ['subdomain'], unique=True)

    with op.batch_alter_table('wards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_charge', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('doctor_charge', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('nursing_charge', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bio_medical_wastage_charge', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wards', schema=None) as batch_op:
        pass

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_subdomain'))

    with op.batch_alter_table('periodontal_exams', schema=None) as batch_op:
        pass

    with op.batch_alter_table('patients', schema=None) as batch_op:
        pass

    with op.batch_alter_table('ortho_records', schema=None) as batch_op:
        pass

    with op.batch_alter_table('operation_theaters', schema=None) as batch_op:
        pass

    with op.batch_alter_table('opd_visits', schema=None) as batch_op:
        pass

    with op.batch_alter_table('ipd_admissions', schema=None) as batch_op:
        pass

    with op.batch_alter_table('insurance_claims', schema=None) as batch_op:
        pass

    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        pass

    with op.batch_alter_table('doctor_schedules', schema=None) as batch_op:
        pass

    with op.batch_alter_table('doctor_profiles', schema=None) as batch_op:
        pass

    with op.batch_alter_table('dental_treatment_plans', schema=None) as batch_op:
        pass

    with op.batch_alter_table('dental_lab_orders', schema=None) as batch_op:
        pass

    with op.batch_alter_table('dental_3d_scans', schema=None) as batch_op:
        pass

    with op.batch_alter_table('communication_logs', schema=None) as batch_op:
        pass

    # ### end Alembic commands ###
