"""Add is_deleted to User and Hospital

Revision ID: 3925b046fb45
Revises: a5a41c3994c0
Create Date: 2026-05-03 15:38:35.133432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3925b046fb45'
down_revision: Union[str, None] = 'a5a41c3994c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    op.drop_column('hospitals', 'is_deleted')
    # ### end Alembic commands ###
