"""add_trial_ends_at_to_hospital

Revision ID: 80fdf553c5a1
Revises: 2f850dd0b608
Create Date: 2026-05-28 17:34:52.086408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80fdf553c5a1'
down_revision: Union[str, None] = '2f850dd0b608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('trial_ends_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospitals', 'trial_ends_at')
    # ### end Alembic commands ###
