"""Add dental fields to Patient model

Revision ID: b78be8167775
Revises: 3925b046fb45
Create Date: 2026-05-03 15:41:26.594850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b78be8167775'
down_revision: Union[str, None] = '3925b046fb45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('specialty', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('opd_number', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('chief_complaint', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('allergies', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('medications', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('prescriptions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'prescriptions')
    op.drop_column('patients', 'medications')
    op.drop_column('patients', 'allergies')
    op.drop_column('patients', 'chief_complaint')
    op.drop_column('patients', 'opd_number')
    op.drop_column('patients', 'specialty')
    # ### end Alembic commands ###
