"""Redirect dental relationships to Patient model

Revision ID: cc7fe2021d9e
Revises: b78be8167775
Create Date: 2026-05-03 15:44:15.052263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc7fe2021d9e'
down_revision: Union[str, None] = 'b78be8167775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'communication_logs', type_='foreignkey')
    op.create_foreign_key(None, 'communication_logs', 'patients', ['patient_id'], ['record_id'])
    op.drop_constraint(None, 'dental_3d_scans', type_='foreignkey')
    op.create_foreign_key(None, 'dental_3d_scans', 'patients', ['patient_id'], ['record_id'])
    op.drop_constraint(None, 'dental_lab_orders', type_='foreignkey')
    op.create_foreign_key(None, 'dental_lab_orders', 'patients', ['patient_id'], ['record_id'])
    op.drop_constraint(None, 'dental_treatment_plans', type_='foreignkey')
    op.create_foreign_key(None, 'dental_treatment_plans', 'patients', ['patient_id'], ['record_id'])
    op.drop_constraint(None, 'dental_treatments', type_='foreignkey')
    op.create_foreign_key(None, 'dental_treatments', 'patients', ['patient_id'], ['record_id'])
    op.drop_constraint(None, 'insurance_claims', type_='foreignkey')
    op.create_foreign_key(None, 'insurance_claims', 'patients', ['patient_id'], ['record_id'])
    op.drop_constraint(None, 'ortho_records', type_='foreignkey')
    op.create_foreign_key(None, 'ortho_records', 'patients', ['patient_id'], ['record_id'])
    op.drop_constraint(None, 'periodontal_exams', type_='foreignkey')
    op.create_foreign_key(None, 'periodontal_exams', 'patients', ['patient_id'], ['record_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'periodontal_exams', type_='foreignkey')
    op.create_foreign_key(None, 'periodontal_exams', 'dental_patients', ['patient_id'], ['patient_id'])
    op.drop_constraint(None, 'ortho_records', type_='foreignkey')
    op.create_foreign_key(None, 'ortho_records', 'dental_patients', ['patient_id'], ['patient_id'])
    op.drop_constraint(None, 'insurance_claims', type_='foreignkey')
    op.create_foreign_key(None, 'insurance_claims', 'dental_patients', ['patient_id'], ['patient_id'])
    op.drop_constraint(None, 'dental_treatments', type_='foreignkey')
    op.create_foreign_key(None, 'dental_treatments', 'dental_patients', ['patient_id'], ['patient_id'])
    op.drop_constraint(None, 'dental_treatment_plans', type_='foreignkey')
    op.create_foreign_key(None, 'dental_treatment_plans', 'dental_patients', ['patient_id'], ['patient_id'])
    op.drop_constraint(None, 'dental_lab_orders', type_='foreignkey')
    op.create_foreign_key(None, 'dental_lab_orders', 'dental_patients', ['patient_id'], ['patient_id'])
    op.drop_constraint(None, 'dental_3d_scans', type_='foreignkey')
    op.create_foreign_key(None, 'dental_3d_scans', 'dental_patients', ['patient_id'], ['patient_id'])
    op.drop_constraint(None, 'communication_logs', type_='foreignkey')
    op.create_foreign_key(None, 'communication_logs', 'dental_patients', ['patient_id'], ['patient_id'])
    # ### end Alembic commands ###
