"""add session_type to DoctorSchedule

Revision ID: e30cb1654e36
Revises: 80fdf553c5a1
Create Date: 2026-05-29 18:59:14.672083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e30cb1654e36'
down_revision: Union[str, None] = '80fdf553c5a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_schedules', sa.Column('session_type', sa.String(), nullable=True, server_default='OPD'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_schedules', 'session_type')
    # ### end Alembic commands ###
